### ISSUE TITLE
Does not work when used in virtual directory

### ISSUE THREAD

**Issue by TheJayMann** [chrisdrobison/aspnetcore-wsfed#10]
When running in IIS or IIS Express, specifying an application root directory as anything other than "/", authentication always fails.  Kestrel behind IIS is smart enough to know what the application base url is, and can separate it into Request.PathBase and Request.Path.  Also, these properties are of type PathString, which override Equals and op_Equals, to provide case insensitive comparisons.  And, the definition of HandleRequestAsync in RemoveAuthenticationHandler compares Request.Path with Options.CallbackPath.

The first problem is that HandleRemoteAuthenticateAsync compares the CallbackPath with the concatenation of Request.PathBase and Request.Path.  The problem here is that now my application is not deployment portable.  If I develop with http://localhost:5000/, but deploy to https://domain/app/, then, during development, CallbackPath will be compared with /signin-wsfed, while in production it will be compared with /app/signin-wsfed.  Rather, if only Request.Path is used, then it would be compared with /signin-wsfed in both cases.

The second problem is that RemoteAuthenticationHandler is already doing exactly this.  Thus, in the production case of having the application hosted in https://domain/app/, when I use a CallbackPath of /signin-wsfed, HandleRequestAsync compares /signin-wsfed with /signin-wsfed, which succeeds, and continues the code down HandleRemoteAuthenticateAsync, which then compares /signin-wsfed with /app/signin-wsfed, which fails, causing authentication to be skipped.  If I alter CallbackPath to instead be /app/signin-wsfed, HandleRequestAsync compares /app/signin-wsfed with /signin-wsfed, which fails, and the entire process is skipped.

I believe the correct solution here is to not compare CallbackPath with Request.Path at all in HandleRemoteAuthenticateAsync, because, if that method is being called, then the work has already been done to determine whether or not to skip handling authentication based on the current path.  Also, in a future release of Microsoft.AspNetCore.Authentication, it appears that a method called ShouldHandleRequestAsync will be added, allowing a derived class to choose itself how authentication requests should be filtered.

**Comment by chrisdrobison** [comment]
If you would like to submit a pull request, that would be great. I designed
this middle ware after the open id one which is where that comparison came
from I believe.

**Comment by TheJayMann** [comment]
I won't be able to get to it now, but I have done the work already, so it shouldn't take much to fork and apply the changes when I can get around to it.
