### ISSUE TITLE
Not working with .NET Core 2.0 Preview 2

### ISSUE THREAD

**Issue by Compufreak345** [chrisdrobison/aspnetcore-wsfed#12]
Hi,

I am currently trying to get this to run with .NET Core 2.0 Preview 2 - I tried using multi-targeting like I did succesfully in .NET Core 1.1, but a colleague told me this should not necessary anymore (and it didn't compile when I tried). In fact, I can even build if I just leave it single-targeted to netcoreapp 2.0, but I get the following warnings & error - I'm not sure if this is related to the library or has something to do with my project setup:

![image](https://user-images.githubusercontent.com/10026694/27900770-ded888e0-622f-11e7-926e-5ca26d3bc7e4.png)

![image](https://user-images.githubusercontent.com/10026694/27900778-e6a22bd0-622f-11e7-96bf-3fcd0a8458ec.png)

That's how I implemented your package (the parts differing from the sample app, according to https://weblog.west-wind.com/posts/2017/May/15/Upgrading-to-NET-Core-20-Preview ):

```
services.AddCookieAuthentication(o =>
          {
            o.LoginPath = "/account/login";
            o.LogoutPath = "/account/logout";
          });
```

```
app.UseAuthentication();
          app.UseWsFederationAuthentication(new WsFederationAuthenticationOptions
          {
            Wtrealm = adfsSettings.GetValue<string>("Wtrealm"),
            MetadataAddress =
              adfsSettings.GetValue<string>("Metadata")

          });
```

I might be able to fix this myself if somebody can give me a hint in the right direction.

Thanks & best regards,
Compu

**Comment by chrisdrobison** [comment]
Looks like some of the underlying classes may have changed in preview 2. At
this point, there are no plans to get this working with 2.0 as Microsoft
will either have or be close to having their own WsFed support by RTM.

**Comment by Compufreak345** [comment]
Thanks for the update, I'll try Microsofts WsFed nightly sometime soon, as it's a bit unclear if it is usable right now. This is the newest statement I found: 

> we are moving along nicely. Our 5.2.0 drops on myget https://www.myget.org/gallery/azureadwebstacknightly have the latest.
> 
> We have the primitive support for WsFed metadata, Saml2Tokens with signature validation.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/595#issuecomment-313253088

**Comment by YaoNiGu** [comment]
I have the same problem.
Any news for this?

**Comment by chrisdrobison** [comment]
At this point in time, I have no plans to update this library for 2.0 as the WsFed support is supposed to be released with ASP.NET Core 2.1 in Q4. I'd welcome a pull request.
