### ISSUE TITLE
How can we add support for Token.Jwt(5.1.2) or update to IdentityModel.Protocols.WsFederation 2

### ISSUE THREAD

**Issue by nikhilsarvaiye** [chrisdrobison/aspnetcore-wsfed#13]
It is currently with 4.0.4, which makes difficult to integrate with IdentityModel.Protocols 2.1.2

**Comment by chrisdrobison** [comment]
I'd welcome a pull request. I have a feeling that there would be some big dependency conflicts.

**Comment by nikhilsarvaiye** [comment]
Yes there quite as in version 2, system.identitymodel.protocol.extensions decoupled to microsoft.identitymodel.tokens and protocol

Also, version 1 used JWT 4.0.4 where as version 2 used >= 5.1.2

I will check for PR, but feels like need to wait for WSFederation beta release.
