### ISSUE TITLE
Does not work in app where newer(5.0+) System.identityModel.tokens.jwt.dll is referenced

### ISSUE THREAD

**Issue by gl2007** [chrisdrobison/aspnetcore-wsfed#14]
My project has 5.+ version of system.identitymodel.tokens.jwt.dll referenced because of some other components used. The WSFederation library gives errors saying some types are not found.

**Comment by gl2007** [comment]
@Chris, I have been able to work around this issue by changing your code to not use the methods/types from the JWT dll. Do you think I should submit a PR if it is ok with you?

**Comment by chrisdrobison** [comment]
Sure, I'll look at it.
