### ISSUE TITLE
Migrating from a .net framework application: missing features?

### ISSUE THREAD

**Issue by epot** [chrisdrobison/aspnetcore-wsfed#16]
Hello,

I am trying to see how to migrate my existing .net framework application to asp.net core using this library. I cannot see an equivalent of PassiveRedirectEnabled in the new Microsoft.IdentityModel.Protocols.WsFederationConfiguration. Do you know if it is possible to have the same behavior for free?

Thanks!

**Comment by chrisdrobison** [comment]
I believe there is a property called AuthenticationMode that will do what
you want.
