### ISSUE TITLE
Store the original token in the claims

### ISSUE THREAD

**Issue by epot** [chrisdrobison/aspnetcore-wsfed#17]
To be able to retrieve the original token from the claims and call collateral services, I would need the WsFederationAuthenticationHandler to add the original token to the claims.

Something like that (the first line comes from the existing implementation so that you see where I would do that):

    var principal = Options.SecurityTokenHandlers.ValidateToken(token, tvp, out parsedToken);

    if (parsedToken != null)
    {
        ClaimsIdentity identity = principal.Identity as ClaimsIdentity;
        if (identity != null)
        {
            StringBuilder sb = new StringBuilder();
            var writer = XmlWriter.Create(new StringWriter(sb), new XmlWriterSettings
            {
                OmitXmlDeclaration = true
            });
            Options.SecurityTokenHandlers[parsedToken].WriteToken(writer, parsedToken);
            writer.Flush();
            identity.AddClaim(new Claim("access_token", Convert.ToBase64String(Encoding.UTF8.GetBytes(sb.ToString()))));
        }
    }

Is it something that would interest you as a pull request (using an option of course)?

**Comment by chrisdrobison** [comment]
Sure

**Comment by epot** [comment]
Awesome, it would avoid an ugly copy&paste :D. I will submit that asap.

**Comment by epot** [comment]
Here we go, I submitted a PR. Let me know what you think of this first implementation.
