### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by another-guy** [chrisdrobison/aspnetcore-wsfed#21]
Hello Chris!

Thank you for putting effort into this library.  Do you have any plans on writing the documentation for it or at least updating the README.md with a reference to the existing documentation that describes the consumption of the library and high level ideas about the underlying machinery?

**Comment by chrisdrobison** [comment]
The short answer is no. The source code provides an example of how to use
this library. The purpose of this library is to fill a gap until Microsoft
officially supports WSFed, which will be in the next couple of months.
After that, I would hope that all users of this library migrate to that. I
actually don't use this library any more as we were able to moved to Open
ID Connect.

**Comment by another-guy** [comment]
Fair enough.
