### ISSUE TITLE
BootstrapContext in ClaimsIdentity is always null even if SaveSigninToken is set to true

### ISSUE THREAD

**Issue by homam1** [chrisdrobison/aspnetcore-wsfed#22]
I set the SaveSigninToken to true in the configuration but still 

claimsIdentity.BootstrapContext is coming always null.

Any idea ?

**Comment by chrisdrobison** [comment]
I have not idea. But, I would recommend that you try out the new WsFed middleware Microsoft has released in preview as I will no longer be updating this library: aspnet/Security#1473

**Comment by homam1** [comment]
I found a solutıon ın BootstrapClaimName
