### ISSUE TITLE
Callback endpoint doesn't seem to handle wsignoutcleanup1.0 message from AD FS 2016

### ISSUE THREAD

**Issue by ghost** [chrisdrobison/aspnetcore-wsfed#4]
When you signout from on-prem AD FS, it sends the above mentioned message to the callback endpoint. The handler however does not seem to expect said message and returns an angry **500** back to AD FS,
with the body content from the developerexceptionpage.

Took me a while to realize where that went .. 😄 ..

You could of course call it cosmetic,
but I would prefer a nice **200** response with a content-length of zero.

**Comment by chrisdrobison** [comment]
Did the original middleware handle that?

**Comment by ghost** [comment]
The original code sends the message to / and the application responds with a **200** and sends that page.

I'm not sure I like that either to be honest. It doesn't need to bleed any body content through to AD FS.
The main difference is that it returns a **200** instead of the angry **500** page.

**Comment by chrisdrobison** [comment]
I would welcome a pull request to help out with this

**Comment by ghost** [comment]
Here you are.

While I'm at it, I want to thank you for making this possible. This is the first time since the release of aspnetcore that I am able to sign-in _**and**_ sign-out of an on-prem AD FS.
Sure, I like all the new OIDC stuff, but I have yet to figure out how to make AD FS 2016 expose it's end_session endpoint so I can sign-out of that too.

Now, onto finding out why the `User.Claims` collection ends up with all duplicate entries...

**Comment by chrisdrobison** [comment]
Fixed by #5
