### ISSUE TITLE
Not an issue, rather question

### ISSUE THREAD

**Issue by alexandis** [chrisdrobison/aspnetcore-wsfed#7]
Hi Chris,
new here - so not sure how i may contact you in other way.
So i'm a bit confused with this: "This is a port of the Katana WsFederation middleware for **ASP.NET Core**. This project has a **hard dependency on the full .NET Framework**..." sounds a bit contradictory to me.
Since .NET Core run-time is a light-weight rival of .NET Framework run-time, if the project has hard dependency on the full .NET Framework, how it can be "for" .NET Core? I mean if I add this implementation to my .NET Core solution, it will just stop being a .NET Core solution, fix me if I'm wrong? :) Just can't figure it out, sorry if my question sounds silly :)

**Comment by chrisdrobison** [comment]
You are confusing ASP.NET Core and .NET Core as the same thing--they are
not. ASP.NET Core (a web framework) can run on top of .NET Core (a runtime,
which is cross platform) or the full .NET Framework (a runtime, which is
Windows only). This library was designed to work with the new ASP.NET Core
web framework, but depends on BCLs that only exist in the full .NET
Framework at this precise moment. Does that make more sense?

**Comment by alexandis** [comment]
Thanks Chris, this makes a perfect sense. I've really confused ASP.NET Core and .NET Core ;-)
So if i got it right now, in case I need WS-Fed support in .NET Core - I must wait for dsig and WS-Fed/SAML token class implementation (AzureAD 5.2.0 milestone at 20th of May) and then - for adding them to next .NET Core version (2.0 in Q3 2017?)
