### ISSUE TITLE
Update to new WsFed Impl

### ISSUE THREAD

**Issue by leastprivilege** [chrisdrobison/aspnetcore-wsfed#8]
Hey - 

have you seen this

https://github.com/aspnet/Security/issues/43#issuecomment-299607475

it seems there are nightlies now that you could use...

**Comment by chrisdrobison** [comment]
Are those nightlies on MyGet?

**Comment by leastprivilege** [comment]
Seems so

**Comment by chrisdrobison** [comment]
@leastprivilege Do you have an inkling on how the removal of Microsoft.IdentityModel.Protocol.Extensions maps into this new world? It looks like there was a ValidateToken call that no longer exists.

**Comment by leastprivilege** [comment]
i need more context

**Comment by DaleMckeown** [comment]
Is there any work being done on this, guys?

**Comment by chrisdrobison** [comment]
I haven't had much of a chance to look at it. The API had changed so I'm
not quite sure how it maps right now.

**Comment by 616b2f** [comment]
@leastprivilege at the moment i try to use your WsFederation example to build an WsFed module for IdSrv4 with the new WsFed implementation from Microsoft (my repo [https://github.com/616b2f/IdentityServer4.WsFederation](url)). After that i could help you out here @chrisdrobison.
