### ISSUE TITLE
Failure when using .NET 4.6 or higher

### ISSUE THREAD

**Issue by jrolstad** [chrisdrobison/aspnetcore-wsfed#9]
When running under the .NET 4.7 framework, an exception is thrown during application startup:

_Inheritance security rules violated by type: 'System.Net.Http.WebRequestHandler'. Derived types must either match the security accessibility of the base type or be less accessible._

I was  able to reproduce this by running the Sample application under .NET 4.6 and higher; .NET 4.5.2 was functional.

**Comment by chrisdrobison** [comment]
I may not have time to look at this for a bit.

**Comment by Addisco** [comment]
Opened #11 for this.
Workaround: Adding a dependency to the System.Net.Http NuGet package in the consuming Web App works as well.
